name: base
channels:
- conda-forge
dependencies:
- appnope=0.1.3
- asttokens=2.4.1
- attrs=23.1.0
- bcrypt=4.1.1
- black=23.11.0
- build=0.7.0
- bzip2=1.0.8
- ca-certificates=2023.11.17
- cffi=1.16.0
- click=8.1.7
- colorama=0.4.6
- comm=0.1.4
- coverage=7.3.2
- cryptography=41.0.7
- debugpy=1.8.0
- decorator=5.1.1
- exceptiongroup=1.2.0
- executing=2.0.1
- flake8=6.1.0
- importlib-metadata=7.0.0
- importlib_metadata=7.0.0
- importlib_resources=6.1.1
- iniconfig=2.0.0
- ipykernel=6.26.0
- ipython=8.18.1
- jedi=0.19.1
- jsonschema=4.20.0
- jsonschema-specifications=2023.11.2
- jupyter_client=8.6.0
- jupyter_core=5.5.0
- libblas=3.9.0
- libcblas=3.9.0
- libcxx=16.0.6
- libexpat=2.5.0
- libffi=3.4.2
- libgfortran=5.0.0
- libgfortran5=13.2.0
- liblapack=3.9.0
- libopenblas=0.3.25
- libsodium=1.0.18
- libsqlite=3.44.2
- libzlib=1.2.13
- llvm-openmp=17.0.6
- markdown-it-py=3.0.0
- matplotlib-inline=0.1.6
- mccabe=0.7.0
- mdurl=0.1.0
- mypy_extensions=1.0.0
- nbformat=5.9.2
- ncurses=6.4
- nest-asyncio=1.5.8
- numpy=1.26.2
- openssl=3.2.0
- packaging=23.2
- pandas=2.1.3
- paramiko=3.3.1
- parso=0.8.3
- pathspec=0.11.2
- pep517=0.13.0
- pexpect=4.8.0
- pickleshare=0.7.5
- pip=23.3.1
- pkgutil-resolve-name=1.3.10
- platformdirs=4.0.0
- pluggy=1.3.0
- prompt-toolkit=3.0.41
- psutil=5.9.5
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pycodestyle=2.11.1
- pycparser=2.21
- pyflakes=3.1.0
- pygments=2.17.2
- pynacl=1.5.0
- pytest=7.4.3
- python=3.12.0
- python-dateutil=2.8.2
- python-dotenv=1.0.0
- python-fastjsonschema=2.19.0
- python-tzdata=2023.3
- python_abi=3.12
- pytz=2023.3.post1
- pyzmq=25.1.1
- readline=8.2
- referencing=0.31.1
- rich=13.7.0
- rpds-py=0.13.2
- setuptools=68.2.2
- six=1.16.0
- stack_data=0.6.2
- tk=8.6.13
- tomli=2.0.1
- tornado=6.3.3
- traitlets=5.14.0
- typing_extensions=4.8.0
- tzdata=2023c
- wcwidth=0.2.12
- wheel=0.42.0
- xz=5.2.6
- zeromq=4.3.5
- zipp=3.17.0

